"""Order persistence Application boundary."""

from quantiqmt.order.application.persistence.errors import (
    IdempotencyConflict,
    JournalCommitFailed,
    OrderJournalCorrupted,
    OutboxClaimLost,
    PersistenceError,
    SnapshotInvalid,
    UniqueIdentifierCollision,
)
from quantiqmt.order.application.persistence.messages import (
    build_order_registered_envelope,
    build_order_status_changed_envelope,
    deterministic_message_id,
)
from quantiqmt.order.application.persistence.model import (
    ClaimedMessage,
    ClaimPolicy,
    ClientOrderIdCandidate,
    JournalAppend,
    OrderCommit,
    OrderRegistration,
    OrderRegistrationDraft,
    OrderSnapshot,
    OutboxMutationResult,
    PersistedOrder,
    PublishFailure,
    RecoveryLoad,
    RecoveryPage,
    RegisterOutcome,
    SnapshotLookup,
)
from quantiqmt.order.application.persistence.serialization import (
    canonical_json_bytes,
    journal_checksum,
    journal_with_registration_fingerprint,
    order_state_payload,
    registration_fingerprint,
    registration_to_payload,
    snapshot_checksum,
    snapshot_payload_without_checksum,
)

__all__ = [
    "ClaimPolicy",
    "ClaimedMessage",
    "ClientOrderIdCandidate",
    "IdempotencyConflict",
    "JournalAppend",
    "JournalCommitFailed",
    "OrderCommit",
    "OrderJournalCorrupted",
    "OrderRegistration",
    "OrderRegistrationDraft",
    "OrderSnapshot",
    "OutboxClaimLost",
    "OutboxMutationResult",
    "PersistedOrder",
    "PersistenceError",
    "PublishFailure",
    "RecoveryLoad",
    "RecoveryPage",
    "RegisterOutcome",
    "SnapshotInvalid",
    "SnapshotLookup",
    "UniqueIdentifierCollision",
    "build_order_registered_envelope",
    "build_order_status_changed_envelope",
    "canonical_json_bytes",
    "deterministic_message_id",
    "journal_checksum",
    "journal_with_registration_fingerprint",
    "order_state_payload",
    "registration_fingerprint",
    "registration_to_payload",
    "snapshot_checksum",
    "snapshot_payload_without_checksum",
]
